# CI speed could be greatly increased by caching node modules and pre-building and storing a cypress image

stages:
  - test
  - cypress_test
  - build

test:
  stage: test
  image: cypress/base:10
  script:
    - yarn
    - yarn bootstrap
    - yarn test

cypress_test:
  stage: cypress_test
  image: cypress/base:10
  script:
    - yarn
    - yarn bootstrap
    - yarn cypress

build:
  stage: build
  image: cypress/base:10
  script:
    - yarn
    - yarn bootstrap
    - yarn build
